Add input component
codelittinc/agnostic-design-system pull request #31
Opened 2020-11-12 12:38 UTC by Rheniery

If applied, pull request will add the input component to the project

### Other minor changes:
N/A

### Card Link:
N/A

### Design Expected Screenshot
N/A

### Implementation Screenshot or GIF
N/A

### Notes:
N/A

2020-11-12 13:38 UTC, kaiomagalhaes requested changes

2020-11-12 13:38 UTC, kaiomagalhaes commented on src/components/Input/DefaultInput/index.tsx
> +interface Props {
please sort these alphabetically

2020-11-12 13:38 UTC, kaiomagalhaes commented on src/index.tsx
> +export { default as Input } from '@/components/Input';
please place this on line 2

2020-11-12 13:38 UTC, kaiomagalhaes commented on src/components/Input/DefaultInput/index.tsx
> +  className: string;
you need to receive the value as well

2020-11-12 17:24 UTC, diogoribeiro commented on src/components/Input/SimpleInput/SimpleInput.css
> +:root {
we also need the properties for the placeholder

2020-11-12 19:13 UTC, diogoribeiro commented on src/components/Input/DefaultInput/DefaultInput.css
> +  outline-color: var(--input-outline-color-focus);
we also need the:
- font-size
- color
- font-weight

2020-11-13 13:36 UTC, diogoribeiro approved these changes

2020-11-13 13:43 UTC, merged