Add Donut Chart component
codelittinc/agnostic-design-system pull request #313
Opened 2021-11-09 22:50 UTC by branquinhoaa

If applied, this pull request will add the Donut Chart component to ADS.

### Other minor changes:
 - Create the documentation for the Chart

### Card Link:
closes #306 

### Design Expected Screenshot
![image](https://user-images.githubusercontent.com/15239141/141017963-1857bf91-406f-4ccd-b50c-7fabd83af1b4.png)

### Implementation Screenshot or GIF
[demo](https://jmp.sh/lelXWMS)

2021-11-09 23:25 UTC, branquinhoaa commented on src/components/DonutChart/DonutChart.stories.tsx
> +  value: 55,
Add a case where we have some custom styles.

2021-11-10 10:46 UTC, kaiomagalhaes requested changes

2021-11-10 10:46 UTC, kaiomagalhaes commented on src/components/DonutChart/DonutChart.stories.mdx
> +|        Prop        |  Type  |                                                      Description                                                       | Default | Mandatory |
@branquinhoaa is it possible to recreate exactly the donut in the picture on https://github.com/codelittinc/agnostic-design-system/issues/306 with these props? I'm not seeing how we would add the `risk` message an icon there

2021-11-10 10:46 UTC, kaiomagalhaes commented on src/components/DonutChart/DonutChart.stories.mdx
> +|        Prop        |  Type  |                                                      Description                                                       | Default | Mandatory |
In the issue I make a suggestion about how we could achieve it

2021-11-10 10:46 UTC, kaiomagalhaes commented on src/components/DonutChart/DonutChart.stories.mdx
> +|       value        | number |                        Receives the percentage of the filled portion we will show on the chart                         |    -    |   true    |
instead of value, maybe we could replace it by `completion` given it is more specific to what we are using this prop for

2021-11-11 16:47 UTC, kaiomagalhaes approved these changes

2021-11-11 16:47 UTC, merged