Add variable classname to toggle
codelittinc/agnostic-design-system pull request #316
Opened 2021-11-12 16:11 UTC by branquinhoaa

If applied, this pull request will allow consumers to pass variable class names to toggle wrapper.

### Other minor changes:
 N/A

### Card Link:
N/A

### Design Expected Screenshot
N/A

### Implementation Screenshot or GIF
N/A

### Notes:
N/A

2021-11-12 16:12 UTC, kaiomagalhaes approved these changes

2021-11-12 16:48 UTC, paulohfev requested changes

2021-11-12 16:48 UTC, paulohfev commented on src/components/Toggle/index.tsx
> +                variablesClassName={classNames(styles['toggle-span'], variablesClassName)}
hey @branquinhoaa could you please add an example showing a custom-styled toggle component?

2021-11-12 20:05 UTC, paulohfev requested changes

2021-11-12 20:05 UTC, paulohfev commented on src/components/Toggle/Toggle.stories.tsx
> +import styles from './ToggleTest.css';
@branquinhoaa could you please rename this file to Toggle.stories.css? This is to maintain consistency in the project architecture.

2021-11-15 17:22 UTC, paulohfev approved these changes

2021-11-15 17:22 UTC, merged