Improve Input component
codelittinc/agnostic-design-system pull request #33
Opened 2020-11-13 17:45 UTC by Rheniery

If applied, pull request will improve the Input component to receive label, message, and description.

### Other minor changes:
 - Categories were removed from the Input component.

### Card Link:
N/A

### Design Expected Screenshot
N/A

### Implementation Screenshot or GIF
![Seleção_117](https://user-images.githubusercontent.com/12198683/99103535-79a80300-25be-11eb-9084-d7c5dd6b42f9.png)

### Notes:
N/A

2020-11-13 17:48 UTC, kaiomagalhaes requested changes

2020-11-13 17:48 UTC, kaiomagalhaes commented on src/components/Input/DefaultInput/DefaultInput.css
> +.span {
please avoid creating classes without a context. A `span` doesn't mean anything other than an HTML tag. A better naming could be 'description'

2020-11-13 17:48 UTC, kaiomagalhaes commented on src/components/Input/DefaultInput/index.tsx
> +  const validateClass = state ? `input--${state}` : '';
this should be a `statusClass`

2020-11-13 17:54 UTC, diogoribeiro commented on src/components/Input/index.tsx
> +import DefaultInput from '@/components/Input/DefaultInput';
We can merge the DefaultInput and the Input component. They're the same component, so it's not necessary to hide the input's implementation in another component

2020-11-13 18:45 UTC, diogoribeiro requested changes

2020-11-13 18:45 UTC, diogoribeiro commented on src/components/Input/index.tsx
> +        type='text'
let's remove this prop. This prop can be handled by the `inputProps`

2020-11-13 18:45 UTC, diogoribeiro commented on src/components/Input/index.tsx
> +  className: string;
this component should allow only the `variablesClassName`. What's the idea of having the `className` prop?

PS.: to modify the input look & feel, the dev needs to use the `variablesClassName` and pass the new values for the variables

2020-11-16 13:59 UTC, kaiomagalhaes requested changes

2020-11-16 13:59 UTC, kaiomagalhaes commented on src/components/Input/Input.stories.tsx
> +export const Default = Template.bind({});
please add a default, positive, and a negative example

2020-11-16 13:59 UTC, kaiomagalhaes commented on src/components/Input/index.tsx
> +Input.defaultProps = {
we don't need to add empty values for the optional attributes.

2020-11-16 14:27 UTC, kaiomagalhaes requested changes

2020-11-16 14:27 UTC, kaiomagalhaes commented on src/components/Input/Input.stories.tsx
> +  state: ''
do you need to pass this attribute?

2020-11-16 14:28 UTC, Rheniery commented on src/components/Input/Input.stories.tsx
> +  state: ''
No. I don't, it's just an example

2020-11-16 14:32 UTC, diogoribeiro approved these changes

2020-11-16 14:36 UTC, merged