Update dropdown adding the top css variable
codelittinc/agnostic-design-system pull request #402
Opened 2022-04-13 21:11 UTC by viniciusaa

If applied, this pull request will fix the dropdown that previously only showed the list on the top position.

### Other minor changes:
 - Add `--dropdown-list-top` CSS variable.

### Card Link:
N/A

### Design Expected Screenshot
N/A

### Implementation Screenshot or GIF
https://user-images.githubusercontent.com/17851720/163270961-147ccfca-5116-46dd-ab09-ef201c932608.mp4

### Notes:
N/A

2022-04-14 12:52 UTC, raphaelsattler requested changes

2022-04-14 12:52 UTC, raphaelsattler commented on src/components/Dropdown/ButtonDropdown/index.tsx
> +        listRef.current.style.setProperty('top', `-${bounds.height}px`);
@viniciusaa, I can see in the implementation video that the dropdown is still going down before it goes up. Could you please fix this? That's not the expected behavior, and it isn't pleasant to see.

2022-04-14 12:52 UTC, raphaelsattler commented on src/components/Dropdown/ButtonDropdown/index.tsx
> +        listRef.current.style.setProperty('top', `-${bounds.height}px`);
If this needs more than just changing the CSS variable, please add a prop for this behaior.

2022-04-15 14:20 UTC, paulohfev commented on src/components/Dropdown/Dropdown.stories.mdx
> +Use the CSS variable ```--dropdown-list-top``` to control the list position.<br />
@viniciusaa can you please make an adjustment to this observation text. We should clarify that both variables are used to control the positioning, however, one of them will be ideal for a given listPosition property.

2022-04-15 15:08 UTC, paulohfev approved these changes

2022-04-15 15:15 UTC, raphaelsattler approved these changes

2022-04-15 15:15 UTC, merged